### ISSUE TITLE
Screenshot discrepancy

### ISSUE THREAD

**Issue by AugWin** [f5devcentral/f5-agility-labs-iam#107]
On https://clouddocs.f5.com/training/community/iam/html/class1/module1/lab03.html, 3.1, Task1, Step 9 it says "Add a Nameserver by entering Address 10.**1**.20.7 and click Add", but the associated screenshot in Step 10 shows 10.**2**.20.7. Users following the screen shot will fail testing at the end of the lab using an incorrect resolver IP.

**Comment by mahdymo** [comment]
Hi, 
It's updated now with a new screenshot
