### ISSUE TITLE
Task 9 - step 4 - the pasword does not exist on the win10 client 

### ISSUE THREAD

**Issue by Klipope** [f5devcentral/f5-agility-labs-iam#90]
This: 
"You will be redirected to Azure AD login page. Login as user1@f5access.onmicrosoft.com and hit Next. The password is stored in a text file named azure_ad_creds.txt on the Win10 Desktop."
does not work anymore.. file is no longer shown on the Desktop :-( 
tried to locate it within the win10 client but no luck. 
or you stored somewhere else.. but i can't find it. 
thanks

**Comment by mahdymo** [comment]
Hi, the passwords are now added to the table in the initial lab index
